export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const LOGIN_EMAIL_SUCCESS = "LOGIN_EMAIL_SUCCESS";
export const LOGIN_EMAIL_REQUEST = "LOGIN_EMAIL_REQUEST";
export const LOGIN_EMAIL_FAILURE = "LOGIN_EMAIL_FAILURE";
export const LOGIN_EMAIL_REFRESH = "LOGIN_EMAIL_REFRESH";
