export const SEND_ACTIVE_CODE = "SEND_ACTIVE_CODE";
export const SEND_ACTIVE_CODE_SUCCESS = "SEND_ACTIVE_CODE_SUCCESS";
export const SEND_ACTIVE_CODE_REQUEST = "SEND_ACTIVE_CODE_REQUEST";
export const SEND_ACTIVE_CODE_FAILURE = "SEND_ACTIVE_CODE_FAILURE";
export const SEND_ACTIVE_CODE_REFRESH = "SEND_ACTIVE_CODE_REFRESH";

export const SIGN_UP_EMAIL = "SIGN_UP_EMAIL";
export const SIGN_UP_EMAIL_SUCCESS = "SIGN_UP_EMAIL_SUCCESS";
export const SIGN_UP_EMAIL_REQUEST = "SIGN_UP_EMAIL_REQUEST";
export const SIGN_UP_EMAIL_FAILURE = "SIGN_UP_EMAIL_FAILURE";
export const SIGN_UP_EMAIL_REFRESH = "SIGN_UP_EMAIL_REFRESH";

export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const LOGIN_EMAIL_SUCCESS = "LOGIN_EMAIL_SUCCESS";
export const LOGIN_EMAIL_REQUEST = "LOGIN_EMAIL_REQUEST";
export const LOGIN_EMAIL_FAILURE = "LOGIN_EMAIL_FAILURE";
export const LOGIN_EMAIL_REFRESH = "LOGIN_EMAIL_REFRESH";

export const FORGOT_PASS_SEND_MAIL = "FORGOT_PASS_SEND_MAIL";
export const FORGOT_PASS_SEND_MAIL_SUCCESS = "FORGOT_PASS_SEND_MAIL_SUCCESS";
export const FORGOT_PASS_SEND_MAIL_REQUEST = "FORGOT_PASS_SEND_MAIL_REQUEST";
export const FORGOT_PASS_SEND_MAIL_FAILURE = "FORGOT_PASS_SEND_MAIL_FAILURE";
export const FORGOT_PASS_SEND_MAIL_REFRESH = "FORGOT_PASS_SEND_MAIL_REFRESH";






